export const Countries = [
  { id: 1, name: 'Afganistán' },
  { id: 2, name: 'Albania' },
  { id: 3, name: 'Alemania' },
  { id: 4, name: 'Andorra' },
  { id: 5, name: 'Angola' },
  { id: 6, name: 'Antigua y Barbuda' },
  { id: 7, name: 'Arabia Saudita' },
  { id: 8, name: 'Argelia' },
  { id: 9, name: 'Argentina' },
  { id: 10, name: 'Armenia' },
  { id: 11, name: 'Australia' },
  { id: 12, name: 'Austria' },
  { id: 13, name: 'Azerbaiyán' },
  { id: 14, name: 'Bahamas' },
  { id: 15, name: 'Bahréin' },
  { id: 16, name: 'Bangladés' },
  { id: 17, name: 'Barbados' },
  { id: 18, name: 'Bielorrusia' },
  { id: 19, name: 'Bélgica' },
  { id: 20, name: 'Belice' },
  { id: 21, name: 'Benín' },
  { id: 22, name: 'Bolivia' },
  { id: 23, name: 'Bosnia y Herzegovina' },
  { id: 24, name: 'Botsuana' },
  { id: 25, name: 'Brasil' },
  { id: 26, name: 'Brunéi' },
  { id: 27, name: 'Bulgaria' },
  { id: 28, name: 'Burkina Faso' },
  { id: 29, name: 'Burundi' },
  { id: 30, name: 'Bután' },
  { id: 31, name: 'Cabo Verde' },
  { id: 32, name: 'Camboya' },
  { id: 33, name: 'Camerún' },
  { id: 34, name: 'Canadá' },
  { id: 35, name: 'Catar' },
  { id: 36, name: 'Chad' },
  { id: 37, name: 'Chile' },
  { id: 38, name: 'China' },
  { id: 39, name: 'Chipre' },
  { id: 40, name: 'Colombia' },
  { id: 41, name: 'Comoras' },
  { id: 42, name: 'Corea del Norte' },
  { id: 43, name: 'Corea del Sur' },
  { id: 44, name: 'Costa de Marfil' },
  { id: 45, name: 'Costa Rica' },
  { id: 46, name: 'Croacia' },
  { id: 47, name: 'Cuba' },
  { id: 48, name: 'Dinamarca' },
  { id: 49, name: 'Dominica' },
  { id: 50, name: 'Ecuador' },
  { id: 51, name: 'Egipto' },
  { id: 52, name: 'El Salvador' },
  { id: 53, name: 'Emiratos Árabes Unidos' },
  { id: 54, name: 'Eritrea' },
  { id: 55, name: 'Eslovaquia' },
  { id: 56, name: 'Eslovenia' },
  { id: 57, name: 'España' },
  { id: 58, name: 'Estados Unidos' },
  { id: 59, name: 'Estonia' },
  { id: 60, name: 'Eswatini' },
  { id: 61, name: 'Etiopía' },
  { id: 62, name: 'Fiji' },
  { id: 63, name: 'Filipinas' },
  { id: 64, name: 'Finlandia' },
  { id: 65, name: 'Francia' },
  { id: 66, name: 'Gabón' },
  { id: 67, name: 'Gambia' },
  { id: 68, name: 'Georgia' },
  { id: 69, name: 'Ghana' },
  { id: 70, name: 'Granada' },
  { id: 71, name: 'Grecia' },
  { id: 72, name: 'Guatemala' },
  { id: 73, name: 'Guinea' },
  { id: 74, name: 'Guinea-Bisáu' },
  { id: 75, name: 'Guinea Ecuatorial' },
  { id: 76, name: 'Guyana' },
  { id: 77, name: 'Haití' },
  { id: 78, name: 'Honduras' },
  { id: 79, name: 'Hungría' },
  { id: 80, name: 'India' },
  { id: 81, name: 'Indonesia' },
  { id: 82, name: 'Irak' },
  { id: 83, name: 'Irán' },
  { id: 84, name: 'Irlanda' },
  { id: 85, name: 'Islandia' },
  { id: 86, name: 'Islas Marshall' },
  { id: 87, name: 'Islas Salomón' },
  { id: 88, name: 'Israel' },
  { id: 89, name: 'Italia' },
  { id: 90, name: 'Jamaica' },
  { id: 91, name: 'Japón' },
  { id: 92, name: 'Jordania' },
  { id: 93, name: 'Kazajistán' },
  { id: 94, name: 'Kenia' },
  { id: 95, name: 'Kirguistán' },
  { id: 96, name: 'Kiribati' },
  { id: 97, name: 'Kuwait' },
  { id: 98, name: 'Laos' },
  { id: 99, name: 'Lesoto' },
  { id: 100, name: 'Letonia' },
  { id: 101, name: 'Líbano' },
  { id: 102, name: 'Liberia' },
  { id: 103, name: 'Libia' },
  { id: 104, name: 'Liechtenstein' },
  { id: 105, name: 'Lituania' },
  { id: 106, name: 'Luxemburgo' },
  { id: 107, name: 'Madagascar' },
  { id: 108, name: 'Malasia' },
  { id: 109, name: 'Malaui' },
  { id: 110, name: 'Maldivas' },
  { id: 111, name: 'Malí' },
  { id: 112, name: 'Malta' },
  { id: 113, name: 'Marruecos' },
  { id: 114, name: 'Mauricio' },
  { id: 115, name: 'Mauritania' },
  { id: 116, name: 'México' },
  { id: 117, name: 'Micronesia' },
  { id: 118, name: 'Moldavia' },
  { id: 119, name: 'Mónaco' },
  { id: 120, name: 'Mongolia' },
  { id: 121, name: 'Montenegro' },
  { id: 122, name: 'Mozambique' },
  { id: 123, name: 'Namibia' },
  { id: 124, name: 'Nauru' },
  { id: 125, name: 'Nepal' },
  { id: 126, name: 'Nicaragua' },
  { id: 127, name: 'Níger' },
  { id: 128, name: 'Nigeria' },
  { id: 129, name: 'Noruega' },
  { id: 130, name: 'Nueva Zelanda' },
  { id: 131, name: 'Omán' },
  { id: 132, name: 'Países Bajos' },
  { id: 133, name: 'Pakistán' },
  { id: 134, name: 'Palaos' },
  { id: 135, name: 'Panamá' },
  { id: 136, name: 'Papúa Nueva Guinea' },
  { id: 137, name: 'Paraguay' },
  { id: 138, name: 'Perú' },
  { id: 139, name: 'Polonia' },
  { id: 140, name: 'Portugal' },
  { id: 141, name: 'Reino Unido' },
  { id: 142, name: 'República Centroafricana' },
  { id: 143, name: 'República Checa' },
  { id: 144, name: 'República del Congo' },
  { id: 145, name: 'República Democrática del Congo' },
  { id: 146, name: 'República Dominicana' },
  { id: 147, name: 'Ruanda' },
  { id: 148, name: 'Rumanía' },
  { id: 149, name: 'Rusia' },
  { id: 150, name: 'Samoa' },
  { id: 151, name: 'San Cristóbal y Nieves' },
  { id: 152, name: 'San Marino' },
  { id: 153, name: 'San Vicente y las Granadinas' },
  { id: 154, name: 'Santa Lucía' },
  { id: 155, name: 'Santo Tomé y Príncipe' },
  { id: 156, name: 'Senegal' },
  { id: 157, name: 'Serbia' },
  { id: 158, name: 'Seychelles' },
  { id: 159, name: 'Sierra Leona' },
  { id: 160, name: 'Singapur' },
  { id: 161, name: 'Siria' },
  { id: 162, name: 'Somalia' },
  { id: 163, name: 'Sri Lanka' },
  { id: 164, name: 'Suazilandia' },
  { id: 165, name: 'Sudáfrica' },
  { id: 166, name: 'Sudán' },
  { id: 167, name: 'Sudán del Sur' },
  { id: 168, name: 'Suecia' },
  { id: 169, name: 'Suiza' },
  { id: 170, name: 'Surinam' },
  { id: 171, name: 'Tailandia' },
  { id: 172, name: 'Tanzania' },
  { id: 173, name: 'Tayikistán' },
  { id: 174, name: 'Timor Oriental' },
  { id: 175, name: 'Togo' },
  { id: 176, name: 'Tonga' },
  { id: 177, name: 'Trinidad y Tobago' },
  { id: 178, name: 'Túnez' },
  { id: 179, name: 'Turkmenistán' },
  { id: 180, name: 'Turquía' },
  { id: 181, name: 'Tuvalu' },
  { id: 182, name: 'Ucrania' },
  { id: 183, name: 'Uganda' },
  { id: 184, name: 'Uruguay' },
  { id: 185, name: 'Uzbekistán' },
  { id: 186, name: 'Vanuatu' },
  { id: 187, name: 'Vaticano' },
  { id: 188, name: 'Venezuela' },
  { id: 189, name: 'Vietnam' },
  { id: 190, name: 'Yemen' },
  { id: 191, name: 'Yibuti' },
  { id: 192, name: 'Zambia' },
  { id: 193, name: 'Zimbabue' }
];
